# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13obObuqZv7QtrYlhVyubSRdNu35N56Te
"""

import pandas as pd
df = pd.read_csv('/content/cleaned_incidents1.csv')

lower = []
for item in df['EventDescription']:
  lower.append(item.lower())
initial_data = df[df['EventDescription'].str.contains("fatal injuries|suffered an injury|died of injuries|sustained an injury|minor injury|minor injuries|work place injury|electric shock injuries were reported|serious injuries|serious injury|possible injury or death|minor bump injury|medical attention for injuries|fatal injury|electric shock injuries were reported|flash injury|injuries unknown|received shock")]

df_new = pd.DataFrame(initial_data, columns = ['ActionTaken', 'Address', 'AssetLabel', 'CauseCommunity', 'CauseEnvironment', 'CausePre', 'CauseTechnical', 'CauseWorkP', 'ContactType', 'CorrectProtection', 'EventDescription', 'FailedAssets', 'FailedExplosion', 'FailedOilFilled', 'FailedOtherAssets', 'FailedOtherAssetsOther', 'FeederNumber', 'IncidentCause', 'IncidentConsequence', 'IncidentDatetime', 'IncidentFireFFactorReportable', 'IncidentFireSeverity', 'IncidentID', 'IncidentLocationType', 'IncidentLocationTypeOther', 'IncidentNumber', 'IncidentType', 'Lat', 'Long', 'MadeSafe', 'NetworkType', 'Status', 'SubmissionID', 'SubmittedDateTimeString', 'Voltage', 'WeatherStation', 'Postcode', 'Locality', 'Category', 'InjuryType'])
type = []
#for value in df_new["EventDescription"]:
for value in df_new["EventDescription"]:
  if ("fatal injuries" in value or "died of injuries" in value or "possible injury" in value or "death" in value or "fatal injury" in value):
    type.append("Fatal")
  elif ("suffered an injury" in value or "work place injury" in value or "electric shock injuries were reported" in value or "serious injuries" in value or "serious injury" in value or "medical attention for injuries" in value or "flash injury" in value or "electric shock" in value or "shock" in value):
    type.append("Major")
  else:
    type.append("Minor")

df_new["InjuryType"] = type 
df_new.to_csv('filtered20.csv')